version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"

  app:
    build:
      context: .
    image: backend
    depends_on:
      - db
    ports:
      - "8086:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
